# Generated by Django 3.2.6 on 2021-10-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
