# Generated by Django 3.2.6 on 2021-11-26 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0002_alter_sede_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad_Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=False)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('cedula', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna_Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidaddosis', models.IntegerField()),
                ('rangoetarioinicio', models.IntegerField()),
                ('rangoetariofin', models.IntegerField()),
                ('periodoentredosis', models.IntegerField()),
                ('tipoenfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.tipo_de_enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidaddedosis', models.IntegerField()),
                ('periodoentredosisdias', models.IntegerField()),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.usuario')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_Tipo_Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('modalidadvacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.modalidad_vacunatorio')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
            ],
        ),
    ]
