# Generated by Django 3.2.6 on 2021-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0003_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad_Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
