# Generated by Django 3.2.6 on 2021-10-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0004_modalidad_vacunatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto_Tipo_Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('modalidadvacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.modalidad_vacunatorio')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
            ],
        ),
    ]
