# Generated by Django 3.2.6 on 2021-10-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0005_puesto_tipo_vacunatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna_Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
            ],
        ),
    ]
