# Generated by Django 3.2.6 on 2021-10-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0006_vacuna_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidaddosis', models.IntegerField(verbose_name=int)),
                ('rangoetarioinicio', models.IntegerField(verbose_name=int)),
                ('rangoetariofin', models.IntegerField(verbose_name=int)),
                ('periodoentredosis', models.IntegerField(verbose_name=int)),
                ('tipoenfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.tipo_de_enfermedad')),
            ],
        ),
    ]
