# Generated by Django 3.2.6 on 2021-10-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0007_tipo_de_enfermedad_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('edad', models.IntegerField(verbose_name=int)),
                ('cedula', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
