# Generated by Django 3.2.6 on 2021-12-14 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacuna', '0007_tipo_de_enfermedad_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('departamento', models.CharField(max_length=150, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='cantidaddosis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='periodoentredosis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='rangoetariofin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='rangoetarioinicio',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UsuarioVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidaddedosis', models.IntegerField()),
                ('periodoentredosisdias', models.IntegerField()),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.usuario')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.vacuna')),
            ],
        ),
    ]
