# Generated by Django 3.2.6 on 2021-10-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0008_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidaddedosis', models.IntegerField(verbose_name=int)),
                ('periodoentredosisdias', models.IntegerField(verbose_name=int)),
                ('puestoname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto')),
                ('usuarioname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.usuario')),
                ('vacunaname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.vacuna')),
            ],
        ),
    ]
