# Generated by Django 3.2.6 on 2021-12-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0008_auto_20211214_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
