# Generated by Django 3.2.6 on 2021-11-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0009_usuariovacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaldeBlanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=100)),
                ('registro', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.profesion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.sede')),
            ],
        ),
    ]
