# Generated by Django 3.2.6 on 2021-12-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0010_alter_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=150, verbose_name='Ciudad')),
            ],
        ),
    ]
