# Generated by Django 3.2.6 on 2022-01-12 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0011_ciudades'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovacuna',
            name='fecha_aplicacion',
            field=models.DateField(null=True, verbose_name='Fecha de aplicacion de dosis'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='cantidaddedosis',
            field=models.IntegerField(verbose_name='Cantidad de dosis'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='periodoentredosisdias',
            field=models.IntegerField(verbose_name='Periodo entre dosis'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='cantidaddosis',
            field=models.IntegerField(verbose_name='Cantidad de dosis'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Plataforma - Marca'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='periodoentredosis',
            field=models.IntegerField(verbose_name='Periodo entre dosis'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='rangoetariofin',
            field=models.IntegerField(verbose_name='Fin de rango etario'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='rangoetarioinicio',
            field=models.IntegerField(verbose_name='Inicio de rango etario'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='tipoenfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.tipo_de_enfermedad', verbose_name='Tipo de enfermedad'),
        ),
    ]
