# Generated by Django 3.2.6 on 2022-01-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0012_auto_20220111_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovacuna',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='fecha_aplicacion',
            field=models.DateField(null=True, verbose_name='Fecha de aplicación de dosis'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='periodoentredosisdias',
            field=models.IntegerField(editable=False, verbose_name='Periodo entre dosis'),
        ),
    ]
