# Generated by Django 3.2.6 on 2022-01-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0013_auto_20220112_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovacuna',
            name='cantidaddedosis',
            field=models.IntegerField(verbose_name='Cantidad de dosis aplicada'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.puesto', verbose_name='Puesto de vacunación'),
        ),
        migrations.AlterField(
            model_name='usuariovacuna',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.vacuna', verbose_name='Marca de Vacuna'),
        ),
    ]
