# Generated by Django 3.2.6 on 2022-01-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0014_auto_20220112_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovacuna',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
