# Generated by Django 3.2.6 on 2022-01-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0017_alter_usuariovacuna_periodoentredosisdias'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='horario_fin',
            field=models.TimeField(null=True, verbose_name='Horario de finalización de atención'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='horario_inicio',
            field=models.TimeField(null=True, verbose_name='Horario de inicio de atención'),
        ),
    ]
