# Generated by Django 3.2.6 on 2022-01-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0019_alter_usuariovacuna_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovacuna',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuna.vacuna', verbose_name='Marca de Vacuna'),
        ),
    ]
